export const EVENTS_HAS_ERRORED = "EVENTS_HAS_ERRORED";

export const EVENTS_IS_LOADING = "EVENTS_IS_LOADING";

export const EVENTS_FETCH_DATA_SUCCESS = "EVENTS_FETCH_DATA_SUCCESS";

export const EVENTS_UPDATE_LOCATION = "EVENTS_UPDATE_LOCATION";
