"""empty message

Revision ID: 51a9c43f0b80
Revises: dccf9917623a
Create Date: 2018-12-23 23:58:53.019338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a9c43f0b80'
down_revision = 'dccf9917623a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('source_id', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'source_id')
    # ### end Alembic commands ###
