"""empty message

Revision ID: 6cc236384480
Revises: 5dadfc5db16d
Create Date: 2018-07-13 19:15:25.954016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc236384480'
down_revision = '5dadfc5db16d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('image', sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speakers', 'image')
    # ### end Alembic commands ###
