"""empty message

Revision ID: dccf9917623a
Revises: 23ee9e7d008e
Create Date: 2018-10-21 09:36:32.175597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dccf9917623a"
down_revision = "23ee9e7d008e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("location", sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "location")
    # ### end Alembic commands ###
