"""empty message

Revision ID: ed60e04bb208
Revises: 
Create Date: 2018-07-07 19:38:27.222508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed60e04bb208'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('photo_url', sa.String(length=2048), nullable=False),
    sa.Column('event_url', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.String(length=50000), nullable=False),
    sa.Column('group_name', sa.String(length=128), nullable=False),
    sa.Column('member_type', sa.String(length=128), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.String(length=50000), nullable=False),
    sa.Column('channel', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('events')
    # ### end Alembic commands ###
