FROM python:3.6.6

# install environment dependencies
RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    netcat \
  && apt-get -q clean

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
ADD ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install -r requirements.txt

# add app
ADD . /usr/src/app

# add newrelic config
ADD ./newrelic.ini /usr/src/app/newrelic.ini

# run server
CMD newrelic-admin run-program gunicorn -b 0.0.0.0:6000 manage:app
