FROM python:3.6.6

# install environment dependencies
RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    netcat \
  && apt-get -q clean

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
ADD ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install -r requirements.txt

# add entrypoint.sh
ADD ./entrypoint-test.sh /usr/src/app/entrypoint-test.sh

# add newrelic config
ADD ./newrelic.ini /usr/src/app/newrelic.ini

# add app
ADD . /usr/src/app

# run server
CMD ["./entrypoint-test.sh"]
