FROM node:8.11.1

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# install and cache app dependencies
ADD package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install react-scripts@1.0.15 -g --silent
RUN npm install npm-run-all -g --silent
RUN npm install node-sass-chokidar -g --silent --unsafe

RUN npm rebuild node-sass

# add app
# ADD . /usr/src/app

# start app
CMD ["npm", "start"]
